### ISSUE TITLE
NameError: mass is not found on habitat_sim but is found on habitat_lab config.

### ISSUE THREAD

**Issue by sktalha68** [Ram81/pirlnav#8]
Hello I am trying to run the eval code. But after setting up habitat and habitat_sim I face the following error:
```
Traceback (most recent call last):
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 233, in _worker_env
    env = env_fn(*env_fn_args)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/utils/env_utils.py", line 32, in make_env_fn
    env = env_class(config=config, dataset=dataset)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/pirlnav/environment.py", line 11, in __init__
    super().__init__(config, dataset)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/env.py", line 374, in __init__
    self._env = Env(config, dataset)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/env.py", line 104, in __init__
    self._sim = make_sim(
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/sims/registration.py", line 19, in make_sim
    return _sim(**kwargs)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 276, in __init__
    self.sim_config = self.create_sim_config(self._sensor_suite)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 309, in create_sim_config
    overwrite_config(
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 78, in overwrite_config
    raise NameError(
NameError: mass is not found on habitat_sim but is found on habitat_lab config.
                    It's also not in the list of keys to ignore: {'sensors', 'is_set_start_state', 'start_position', 'start_rotation'}
                    Did you make a typo in the config?
                    If not the version of Habitat Sim may not be compatible with Habitat Lab version: ANGULAR_ACCELERATION: 12.56
ANGULAR_FRICTION: 1.0
COEFFICIENT_OF_RESTITUTION: 0.0
HEIGHT: 0.88
IS_SET_START_STATE: False
LINEAR_ACCELERATION: 20.0
LINEAR_FRICTION: 0.5
MASS: 32.0
RADIUS: 0.18
SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
START_POSITION: [0, 0, 0]
START_ROTATION: [0, 0, 0, 1]
                    
Exception ignored in: <function Simulator.__del__ at 0x7fd2c03c4f70>
Traceback (most recent call last):
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-sim/src_python/habitat_sim/simulator.py", line 555, in __del__
    self.close(destroy=True)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-sim/src_python/habitat_sim/simulator.py", line 131, in close
    if not self._initialized:
AttributeError: 'HabitatSim' object has no attribute '_initialized'
Traceback (most recent call last):
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/run.py", line 94, in <module>
    main()
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/run.py", line 42, in main
    run_exp(**vars(args))
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/run.py", line 90, in run_exp
    execute_exp(config, run_type)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/run.py", line 75, in execute_exp
    trainer.eval()
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat_baselines/common/base_trainer.py", line 110, in eval
    self._eval_checkpoint(
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/pirlnav/ppo_trainer.py", line 563, in _eval_checkpoint
    self._init_envs(config)
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat_baselines/rl/ppo/ppo_trainer.py", line 203, in _init_envs
    self.envs = construct_envs(
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/utils/env_utils.py", line 113, in construct_envs
    envs = vector_env_cls(
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 193, in __init__
    self.observation_spaces = [
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 194, in <listcomp>
    read_fn() for read_fn in self._connection_read_fns
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 67, in recv
    buf = self.recv_bytes()
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x7f219b5a2b80>
Traceback (most recent call last):
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 592, in __del__
    self.close()
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 460, in close
    read_fn()
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/core/vector_env.py", line 97, in __call__
    res = self.read_fn()
  File "/netscratch/sheikh/Projects/Active/VLN/pirlnav/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 67, in recv
    buf = self.recv_bytes()
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/netscratch/sheikh/anaconda3/envs/pirlnav-t4/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
```

**Comment by youjishiguang** [comment]
Hello, I am also getting the same error, is this a problem with the habitat-sim version, do you have a good solution

**Comment by sktalha68** [comment]
Try this, it worked for me ([reference](https://github.com/Claessens14/pirlnav-fork/issues/1)):
```
commented out NameError() function on line 78
/gpfs/fs0/scratch/l/leil/claess14/pirlnav/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py
```
